### PR TITLE
[fix] Returning to wrong screen after AntiDisconnect

### LINKED ISSUE #1859: Antidisconnect exits game to multiplayer screen
Created by: Voxel (<@245404909229441024>)

 When Antidisconnect is enabled and you attempt to exit a singleplayer world, you will be put on the multiplayer server selection screen. I would expect to be put on the singleplayer world selection screen, as I would be if the module were disabled.

### PR DESCRIPTION
**Pull request by scorbett123**
Go to the correct screen after anti disconnect whilst in single player.

Closes #1859.

### CODE REVIEW

**Comment by l1ving** [comment]
Huh. I thought autolog had the same problem lol

File: src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt [hunk 1]
```diff
@@ -48,6 +42,8 @@ class KamiGuiAntiDisconnect : GuiScreen() {
                             mc.displayGuiScreen(GuiMultiplayer(GuiMainMenu()))
                         }
                     }
+                    mc.world.sendQuittingDisconnectingPacket()
```
Comment (l1ving) [inline src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: why are you sending these after?

Comment (scorbett123) [reply src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: I think that otherwise it believes that you have already left, therefore no integrated server is running, at least this worked in my test and it didn't with these before.

Comment (l1ving) [reply src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: I think that was the intention. I send it in the old order for autolog in order to log out of the server as quickly as possible, I didn't find any issue with doing it the old way

Comment (scorbett123) [reply src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: I will test it further, however I believe that this was the reason it wasn't working.

Comment (scorbett123) [reply src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: Wait, also why do you need anti disconnect to log out quickly? Isn't it meant for stopping that.

Comment (l1ving) [reply src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: I'm saying that AutoLog uses the same order (before you changed it) to log out as fast as possible, and it doesn't have problems.

Comment (scorbett123) [reply src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiAntiDisconnect.kt:45]: Just tested it, yes this does cause an issue having this bit before.

**Review by l1ving — APPROVED** [review]

**Comment by scorbett123** [comment]
Wait, I can copy and paste yet not cause millions of formatting issues?

**Comment by scorbett123** [comment]
No, I am not that good, you just didn't notice.

**Comment by l1ving** [comment]
rofl :pensive:
